title: Github Blog
description: > # this means to ignore newlines until "baseurl:"
  Blog with theme Future Imperfect<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://b-re-w.github.io" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'BREW'
  last_name: 'BREW'
  cv: '//github.io'
  avatar: '/images/avatar.jpeg'
  github_username:  b-re-w  
  email: irack000@github.com
  vk_id: id202102545
  telegram_name: name
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html

port: 4000
future: true
